services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: Prueba_DB
      POSTGRES_USER: JAILER
      POSTGRES_PASSWORD: babahaha19
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: jailerocampo77@gmail.com
      PGADMIN_DEFAULT_PASSWORD: babahaha19
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db-data:
